### PR TITLE
Add rife-v4.13

### PR DESCRIPTION
**Pull request by TNTwise**
Sorry if this is converted incorrectly, I followed the tutorial https://github.com/styler00dollar/VSGAN-tensorrt-docker/issues/37. Param file looks different than other recent conversions, but it works fine on my end.

Edit: Converted 4.12 as well, and the output matches the model here, so I can assume 4.13 is also converted correctly. https://github.com/TNTwise/Rife-Vulkan-Models/releases/tag/4.12

### CODE REVIEW

**Comment by styler00dollar** [comment]
Thanks for doing this. Would you mind to also include the ensemble model? It is a bit hard to verify a model by just looking at the param file, but if output looks good it is probably correct. I will merge once I test it later myself.

**Comment by TNTwise** [comment]
Just made the ensemble model. https://github.com/TNTwise/Rife-Vulkan-Models/releases/tag/4.13-ensemble 4.13-lite didnt export correctly, so I'll try again.

**Comment by hooke007** [comment]
I notice that the size of models exported by others (i.e. https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/blob/master/models/rife-v4.8_ensembleFalse/flownet.bin) is larger than styler00dollar's. What caused it?

**Comment by TNTwise** [comment]
Exporting method I'm assuming.

**Comment by hooke007** [comment]
> because I used convertmodel.com

Try to enable fp16 option.

**Comment by styler00dollar** [comment]
All the models I exported myself are in fp16 and I would prefer if all are. 4.13 is ~10.4mb and 4.13 lite is ~5.19mb.

**Comment by TNTwise** [comment]
Sorry, I'm changing it now.

**Comment by styler00dollar** [comment]
> I notice that the size of models exported by others (i.e. https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/blob/master/models/rife-v4.8_ensembleFalse/flownet.bin) is larger than styler00dollar's. What caused it?

I didn't even notice this. Looks like fp32.

**Comment by TNTwise** [comment]
converted using fp16, thanks for telling me.

**Comment by styler00dollar** [comment]
Tested myself and compared to TensorRT a bit, looks good visually, merging.

**Pull request merged**
