### PR TITLE
Add rife-v3.9 + rife-v4.14-lite

### PR DESCRIPTION
**Pull request by TNTwise**
converted fast true ensemble false and fast false ensemble true, tested with vapoursynth, output looks decent for me but didn't compare directly to pytorch. 3.9 has timestep so it doesn't have the issue of the in2 failed.

### CODE REVIEW

**Comment by hooke007** [comment]
My views...Old models should be removed. We already have the param `model_path` to allow to load those models.

**Comment by TNTwise** [comment]
Makes sense, I'll close this.

**Comment by styler00dollar** [comment]
This plugin is supposed to be a collection of hzwer rife models to make them easily accessible, so I think it would be fine to add this. I didn't have time to test it yet though.

**Comment by TNTwise** [comment]
Just added rife-v4.14-lite, model seems fine but it needs to have convolutiondepthwise set to true.

**Comment by styler00dollar** [comment]
Looks good, thanks.

**Pull request merged**
